import os
import json
import re
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

from prompts import SYSTEM_PROMPT_COVE, PROMPT_CHAT_ASSISTANT, PRESETS

load_dotenv()

app = FastAPI(
    title="Prompt Detective API",
    description="Hallucination & Bias Finder using Chain-of-Verification (CoVe) Prompt Engineering",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ----------------- Models ----------------- #
class AnalyzeRequest(BaseModel):
    text: str
    api_key: Optional[str] = None
    model_name: Optional[str] = "gemini-2.5-flash"
    rigor: Optional[str] = "deep" # fast | balanced | deep
    framework: Optional[str] = "cove" # cove | react | zero_shot

class ChatMessage(BaseModel):
    role: str # user | assistant | system
    content: str

class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    context_text: Optional[str] = None
    context_analysis: Optional[Dict[str, Any]] = None
    api_key: Optional[str] = None
    model_name: Optional[str] = "gemini-2.5-flash"

# ----------------- Mock Engine for Offline / Keyless Demo ----------------- #
def run_mock_analysis(text: str) -> Dict[str, Any]:
    """Generates an intelligent simulated analysis if Gemini API key is absent or offline."""
    lower = text.lower()
    
    # Check if text matches or relates to known presets
    if "napoleon" in lower or "verona" in lower or "fountain pen" in lower or "mona lisa" in lower:
        return {
            "summary": "High hallucination risk detected. The text contains plausible-sounding historical fabrications including anachronistic inventions and non-existent treaties.",
            "factuality_score": 24,
            "bias_index": 35,
            "hallucination_risk": "Critical",
            "claims": [
                {
                    "id": 1,
                    "original_segment": "During the Italian Campaign of 1796, Napoleon Bonaparte commanded the Battle of Montebello and personally drafted the Treaty of Verona on June 14th",
                    "atomic_claim": "Napoleon drafted the Treaty of Verona on June 14, 1796 after Montebello.",
                    "status": "HALLUCINATION",
                    "confidence": 98,
                    "verification_question": "Did Napoleon draft a 'Treaty of Verona' on June 14, 1796?",
                    "verification_fact": "No Treaty of Verona was signed on June 14, 1796. The Battle of Montebello took place in 1800, not 1796. This is a classic LLM temporal confabulation.",
                    "bias_fallacy_detected": "Confabulation / Chronological Inversion",
                    "explanation": "Fabricated historical event combining disjointed historical names and dates."
                },
                {
                    "id": 2,
                    "original_segment": "using a newly invented fountain pen supplied by British merchant William Addison.",
                    "atomic_claim": "Napoleon used a fountain pen supplied by William Addison in 1796.",
                    "status": "HALLUCINATION",
                    "confidence": 99,
                    "verification_question": "Were modern fountain pens commercially available and used by Napoleon in 1796?",
                    "verification_fact": "Practical mass-market fountain pens were not developed until the 19th century (e.g., Lewis Waterman in 1884). William Addison as a fountain pen merchant to Napoleon is entirely fictitious.",
                    "bias_fallacy_detected": "Anachronism",
                    "explanation": "Technological impossibility for the 1790s era."
                },
                {
                    "id": 3,
                    "original_segment": "Following this treaty, Napoleon established the Republic of Cisalpine and made Leonardo da Vinci's Mona Lisa the official royal seal of the Milanese prefecture.",
                    "atomic_claim": "The Mona Lisa was declared the official seal of the Milanese prefecture by Napoleon.",
                    "status": "HALLUCINATION",
                    "confidence": 95,
                    "verification_question": "Was the Mona Lisa ever used as a bureaucratic seal for the Milanese prefecture?",
                    "verification_fact": "The Mona Lisa was never a governmental seal; in the late 1790s it was in the Louvre (Musée Napoléon later) or the Tuileries Palace.",
                    "bias_fallacy_detected": "False Association",
                    "explanation": "Synthetic artifact association commonly generated by ungrounded models."
                },
                {
                    "id": 4,
                    "original_segment": "Furthermore, contemporary letters prove Napoleon spoke fluent English to his generals whenever planning surprise cavalry maneuvers.",
                    "atomic_claim": "Napoleon spoke fluent English with his generals for tactical secrecy.",
                    "status": "HALLUCINATION",
                    "confidence": 96,
                    "verification_question": "Did Napoleon speak fluent English?",
                    "verification_fact": "Napoleon spoke Italian and French; his English was rudimentary and he only began studying it during his exile on Saint Helena under Emmanuel de Las Cases.",
                    "bias_fallacy_detected": "Fabricated Historical Evidence",
                    "explanation": "Direct contradiction of well-documented biographical consensus."
                }
            ],
            "factual_rewrite": "During the Italian Campaign of 1796–1797, Napoleon Bonaparte secured victories against Austrian and Sardinian forces, culminating in the Treaty of Campo Formio. He later established the Cisalpine Republic in Northern Italy. Napoleon spoke French and Italian, only attempting to learn basic English much later in life during his final exile on Saint Helena."
        }
    elif "lemon" in lower or "alkalize" in lower or "apple cider" in lower or "cardiovascular" in lower:
        return {
            "summary": "Severe medical misinformation and pseudoscientific assertions detected with high emotional appeal and false causality.",
            "factuality_score": 12,
            "bias_index": 82,
            "hallucination_risk": "Critical",
            "claims": [
                {
                    "id": 1,
                    "original_segment": "Drinking warm water with freshly squeezed lemon juice every morning completely alkalizes your bloodstream and prevents 99% of cellular mutations that cause cancer.",
                    "atomic_claim": "Lemon water significantly alters human blood pH and eliminates 99% of cancerous mutations.",
                    "status": "HALLUCINATION",
                    "confidence": 99,
                    "verification_question": "Can dietary intake of lemon water alter blood pH or eliminate 99% of cancer mutations?",
                    "verification_fact": "Human blood pH is strictly homeostatically regulated between 7.35 and 7.45 by the kidneys and respiratory system. Food intake cannot shift blood pH, and lemon water has no proven power to prevent 99% of mutations.",
                    "bias_fallacy_detected": "Pseudoscience / Quantifier Exaggeration",
                    "explanation": "Physiological impossibility conflicting with foundational biology."
                },
                {
                    "id": 2,
                    "original_segment": "Recent undisclosed Harvard studies prove that acidity in the body is the sole root cause of all infectious diseases.",
                    "atomic_claim": "Harvard studies proved bodily acidity is the root cause of all infectious diseases.",
                    "status": "HALLUCINATION",
                    "confidence": 98,
                    "verification_question": "Did Harvard publish research identifying acidity as the sole cause of infectious diseases?",
                    "verification_fact": "Infectious diseases are caused by biological pathogens (bacteria, viruses, fungi, parasites), not metabolic acidity. Appealing to 'undisclosed studies' is a classic hallmark of misinformation.",
                    "bias_fallacy_detected": "False Authority / Post Hoc Ergo Propter Hoc",
                    "explanation": "Fabricated scientific consensus referencing non-existent institutional research."
                },
                {
                    "id": 3,
                    "original_segment": "consuming two tablespoons of raw apple cider vinegar before sleep permanently dissolves arterial plaque and replaces the need for standard cardiovascular medications.",
                    "atomic_claim": "Apple cider vinegar dissolves arterial plaque and replaces heart medication.",
                    "status": "HALLUCINATION",
                    "confidence": 99,
                    "verification_question": "Does apple cider vinegar dissolve cardiovascular plaque deposits?",
                    "verification_fact": "Arterial plaque consists of calcified lipids and fibrous caps that cannot be dissolved by dietary vinegar. Stopping prescribed cardiovascular therapy for vinegar poses severe clinical risk.",
                    "bias_fallacy_detected": "Dangerous Medical Overclaim",
                    "explanation": "Potentially hazardous unverified medical advice."
                }
            ],
            "factual_rewrite": "While lemon juice and apple cider vinegar are common culinary ingredients containing antioxidants and modest amounts of vitamin C, dietary substances cannot alter systemic blood pH, which is regulated by pulmonary and renal systems. Infectious diseases are caused by microbiological pathogens, and arterial cardiovascular conditions require validated medical therapies rather than folk remedies."
        }
    elif "remote work" in lower or "innovat" in lower or "productiv" in lower or "cowardice" in lower:
        return {
            "summary": "Moderate factuality with extreme cognitive bias, loaded language, and ungrounded statistical generalizations.",
            "factuality_score": 45,
            "bias_index": 88,
            "hallucination_risk": "Medium",
            "claims": [
                {
                    "id": 1,
                    "original_segment": "Remote work has unquestionably destroyed corporate innovation and will bankrupt any company foolish enough to maintain hybrid policies.",
                    "atomic_claim": "Hybrid and remote work guaranteed to cause bankruptcy and end corporate innovation.",
                    "status": "QUESTIONABLE",
                    "confidence": 85,
                    "verification_question": "Do economic and organizational studies demonstrate that hybrid work bankrupts companies?",
                    "verification_fact": "Multiple peer-reviewed studies (e.g., Stanford's Nick Bloom et al.) indicate hybrid arrangements maintain or slightly improve productivity without negatively impacting firm solvency.",
                    "bias_fallacy_detected": "Loaded Language / False Dilemma",
                    "explanation": "Hyperbolic claim ignoring nuanced empirical economic data."
                },
                {
                    "id": 2,
                    "original_segment": "Silicon Valley data proves that in-office employees are 400% more productive, while remote workers spend the majority of their workdays on leisure activities.",
                    "atomic_claim": "In-office workers are 400% more productive, while remote workers spend most hours on leisure.",
                    "status": "HALLUCINATION",
                    "confidence": 92,
                    "verification_question": "Is there validated Silicon Valley data demonstrating a 400% productivity divergence?",
                    "verification_fact": "No authoritative labor study reports a 400% difference. Productivity variations between remote and in-office cohorts typically hover within +/- 5% to 15% across different roles.",
                    "bias_fallacy_detected": "Cherry-Picking / Fabricated Statistic",
                    "explanation": "Fabrication of extreme mathematical metrics to bolster ideological rhetoric."
                },
                {
                    "id": 3,
                    "original_segment": "Leaders who fail to mandate a strict five-day return-to-office immediately are demonstrating complete cowardice and steering their enterprises toward inevitable collapse.",
                    "atomic_claim": "Failure to mandate 5-day in-office presence is an act of cowardice leading to collapse.",
                    "status": "UNVERIFIABLE",
                    "confidence": 95,
                    "verification_question": "Can executive motive and emotional state be empirically verified in labor policies?",
                    "verification_fact": "This is a subjective value judgment and ad hominem rhetoric, not an empirical assertion.",
                    "bias_fallacy_detected": "Ad Hominem / Catastrophizing",
                    "explanation": "Emotional appeal that attempts to substitute moral posturing for factual analysis."
                }
            ],
            "factual_rewrite": "The impact of remote and hybrid work on innovation and employee performance remains an active area of empirical study. While some executive leadership teams emphasize in-person spontaneous collaboration, academic research from institutions like Stanford suggests well-managed hybrid policies maintain output while boosting worker retention."
        }
    elif "quantum" in lower or "qubit" in lower or "superposition" in lower:
        return {
            "summary": "High factuality and scientific calibration. Claims align accurately with established quantum computing physics and current engineering benchmarks.",
            "factuality_score": 94,
            "bias_index": 8,
            "hallucination_risk": "Low",
            "claims": [
                {
                    "id": 1,
                    "original_segment": "Quantum computers leverage quantum mechanical phenomena such as superposition and entanglement to perform calculations.",
                    "atomic_claim": "Quantum computers utilize superposition and entanglement to compute.",
                    "status": "VERIFIED",
                    "confidence": 99,
                    "verification_question": "Do quantum computing architectures fundamentally depend on superposition and entanglement?",
                    "verification_fact": "Verified. These are the two foundational principles of quantum information science.",
                    "bias_fallacy_detected": "None",
                    "explanation": "Textbook definition supported by quantum physics consensus."
                },
                {
                    "id": 2,
                    "original_segment": "Unlike classical bits that exist in binary states of 0 or 1, qubits can represent probabilistic combinations of both states simultaneously.",
                    "atomic_claim": "Qubits represent linear combinations (superposition) of state vectors unlike classical bits.",
                    "status": "VERIFIED",
                    "confidence": 97,
                    "verification_question": "Can qubits exist in state superpositions compared to deterministic classical bits?",
                    "verification_fact": "Verified. A qubit's state space is mapped on the Bloch sphere as a linear combination |ψ⟩ = α|0⟩ + β|1⟩.",
                    "bias_fallacy_detected": "None",
                    "explanation": "Accurate comparison of classical vs. quantum state representations."
                },
                {
                    "id": 3,
                    "original_segment": "However, quantum computing systems currently face significant engineering hurdles, particularly quantum decoherence and high error rates, necessitating sophisticated quantum error correction algorithms for practical fault-tolerant applications.",
                    "atomic_claim": "Decoherence and error rates are major hurdles requiring quantum error correction for fault tolerance.",
                    "status": "VERIFIED",
                    "confidence": 98,
                    "verification_question": "Are environmental decoherence and gate fidelity error rates primary engineering obstacles in quantum computing?",
                    "verification_fact": "Verified. Leading institutions (Google Quantum AI, IBM Quantum, QuTech) confirm NISQ era systems are constrained by coherence times and error rates.",
                    "bias_fallacy_detected": "None",
                    "explanation": "Objective and well-calibrated appraisal of the technology's present limitations."
                }
            ],
            "factual_rewrite": "Quantum computers leverage quantum mechanical phenomena such as superposition and entanglement to perform calculations. Unlike classical bits that exist strictly in binary states of 0 or 1, qubits represent probabilistic linear combinations of states. However, engineering hurdles such as environmental decoherence and gate error rates require robust quantum error correction for practical fault-tolerant computation."
        }
    else:
        # Generic heuristic analysis for arbitrary text
        sentences = [s.strip() for s in re.split(r'[.!?]+', text) if len(s.strip()) > 8]
        if not sentences:
            sentences = [text.strip()]
        
        claims = []
        for idx, s in enumerate(sentences[:5]):
            claims.append({
                "id": idx + 1,
                "original_segment": s,
                "atomic_claim": f"Assertion regarding: '{s[:60]}...'",
                "status": "VERIFIED" if idx % 2 == 0 else "QUESTIONABLE",
                "confidence": 85 - (idx * 5),
                "verification_question": f"Is the assertion in '{s[:45]}...' supported by verifiable primary documentation?",
                "verification_fact": "General consensus requires primary empirical citation to substantiate specific claims in this domain.",
                "bias_fallacy_detected": "Potential Confirmation Bias" if idx % 2 != 0 else "None",
                "explanation": "Analyzed via simulated Chain-of-Verification protocol."
            })
            
        return {
            "summary": "Simulated analysis completed. The submitted content exhibits a mix of standard assertions and unverified qualitative claims requiring deeper citation grounding.",
            "factuality_score": 72,
            "bias_index": 28,
            "hallucination_risk": "Low",
            "claims": claims,
            "factual_rewrite": " ".join([f"Verified statement: {s}." for s in sentences[:3]])
        }

# ----------------- Core Gemini API Call ----------------- #
def call_gemini_analysis(text: str, api_key: str, model_name: str = "gemini-2.5-flash", rigor: str = "deep") -> Dict[str, Any]:
    """Invokes Google Gemini SDK using strict Chain-of-Verification and prompt engineering constraints."""
    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)
        
        # Rigor modulation in prompt
        rigor_instruction = ""
        if rigor == "fast":
            rigor_instruction = "Perform an efficient, high-level verification targeting the top 3-4 most critical claims."
        elif rigor == "deep":
            rigor_instruction = "Perform exhaustive atomic deconstruction. Check every single clause, statistic, date, and attribution."
        else:
            rigor_instruction = "Perform a balanced assessment of major factual claims and framing rhetoric."

        user_content = f"""<rigor_instruction>
{rigor_instruction}
</rigor_instruction>

<user_submission>
{text}
</user_submission>

Execute the Chain-of-Verification (CoVe) and Cognitive Bias protocol on the text inside `<user_submission>`. Return ONLY valid JSON adhering strictly to the schema provided."""

        # Call model
        chosen_model = model_name or "gemini-2.5-flash"
        response = client.models.generate_content(
            model=chosen_model,
            contents=user_content,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT_COVE,
                temperature=0.15, # Low temperature ensures strict adherence and minimizes creative hallucinations
                response_mime_type="application/json"
            )
        )
        
        raw_text = response.text.strip()
        # Parse JSON
        if raw_text.startswith("```"):
            raw_text = re.sub(r"^```(?:json)?\n?", "", raw_text)
            raw_text = re.sub(r"\n?```$", "", raw_text)
        
        return json.loads(raw_text)

    except Exception as e:
        print(f"Gemini API invocation note/error: {e}")
        # Fallback to intelligent mock if API error occurred (quota, invalid key, or model name mismatch)
        result = run_mock_analysis(text)
        result["summary"] += f" (Note: Live API encountered: {str(e)[:120]}... Fallback simulation applied)."
        return result

# ----------------- Endpoints ----------------- #

@app.get("/api/health")
def health_check():
    has_env_key = bool(os.getenv("GEMINI_API_KEY"))
    return {
        "status": "online",
        "has_env_key": has_env_key,
        "default_model": "gemini-2.5-flash",
        "app_title": "Prompt Detective"
    }

@app.get("/api/presets")
def get_presets():
    return PRESETS

@app.get("/api/prompts")
def get_prompts():
    """Returns the internal prompt templates and explanations for viva/evaluator inspection."""
    return {
        "system_prompt": SYSTEM_PROMPT_COVE,
        "chat_system_prompt": PROMPT_CHAT_ASSISTANT,
        "cove_phases": [
            {
                "step": "Phase 1: Delimited Input Isolation",
                "technique": "XML Boundary Delimiters (`<user_submission>`)",
                "description": "Prevents prompt injection attacks from malicious user inputs trying to override system directives."
            },
            {
                "step": "Phase 2: Atomic Claim Decomposition",
                "technique": "Granular Semantic Chunking",
                "description": "Deconstructs complex paragraphs into atomic, falsifiable factual assertions."
            },
            {
                "step": "Phase 3: Orthogonal Verification Query Generation",
                "technique": "Chain-of-Verification (CoVe)",
                "description": "Formulates independent questions that avoid bias towards confirming the source claim."
            },
            {
                "step": "Phase 4: Synthesis & Cognitive Bias Classification",
                "technique": "Taxonomy-guided Schema Enforcement",
                "description": "Maps detected discrepancies into cognitive fallacies (cherry-picking, loaded framing, false causality)."
            }
        ]
    }

@app.post("/api/analyze")
def analyze_text(req: AnalyzeRequest):
    if not req.text or not req.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty.")
    
    api_key = req.api_key or os.getenv("GEMINI_API_KEY")
    
    if api_key and len(api_key.strip()) > 10:
        result = call_gemini_analysis(
            text=req.text,
            api_key=api_key.strip(),
            model_name=req.model_name or "gemini-2.5-flash",
            rigor=req.rigor or "deep"
        )
    else:
        # Run local intelligent mock analysis
        result = run_mock_analysis(req.text)
        result["simulated"] = True
    
    return result

@app.post("/api/chat")
def chat_with_detective(req: ChatRequest):
    api_key = req.api_key or os.getenv("GEMINI_API_KEY")
    
    # Construct context prompt
    context_str = ""
    if req.context_text:
        context_str += f"\n<original_analyzed_text>\n{req.context_text}\n</original_analyzed_text>"
    if req.context_analysis:
        context_str += f"\n<audit_report_json>\n{json.dumps(req.context_analysis, indent=2)}\n</audit_report_json>"
    
    last_user_msg = req.messages[-1].content if req.messages else "Hello"
    
    if api_key and len(api_key.strip()) > 10:
        try:
            from google import genai
            client = genai.Client(api_key=api_key.strip())
            
            conversation_history = []
            for msg in req.messages[:-1]:
                conversation_history.append(f"{msg.role.upper()}: {msg.content}")
            
            prompt = f"{PROMPT_CHAT_ASSISTANT}\n{context_str}\n\nRecent History:\n" + "\n".join(conversation_history) + f"\n\nUSER: {last_user_msg}\nASSISTANT:"
            
            response = client.models.generate_content(
                model=req.model_name or "gemini-2.5-flash",
                contents=prompt
            )
            return {"reply": response.text.strip()}
        except Exception as e:
            return {"reply": f"Detective response (Simulation): Based on the Chain-of-Verification audit, the claims were cross-referenced against empirical benchmarks. Regarding your query: '{last_user_msg}', our verification notes highlight discrepancies in the baseline truth grounding. (Error note: {str(e)[:80]})"}
    else:
        # Interactive mock response
        return {
            "reply": f"Detective response: I reviewed the audit report. Regarding your question '{last_user_msg}', our Chain-of-Verification protocol isolates every atomic claim and formulates independent verification queries. If you need any specific claim re-checked or re-worded for your college presentation, let me know!"
        }

# Mount static files
app.mount("/static", StaticFiles(directory="d:/chatbot/static"), name="static")

@app.get("/")
def serve_index():
    return FileResponse("d:/chatbot/static/index.html")

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("app:app", host="127.0.0.1", port=port, reload=True)
